apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    image-pull-policy: IfNotPresent
    service.type: NodePort
  creationTimestamp:
  labels:
    io.kompose.service: ad-insertion-frontend
  name: ad-insertion-frontend
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp:
      labels:
        io.kompose.service: ad-insertion-frontend
    spec:
      containers:
      - env:
        - name: AD_DURATION
          value: '5'
        - name: AD_INTERVALS
          value: 4,8
        image: ssai_ad_insertion_frontend:latest
        imagePullPolicy: IfNotPresent
        name: ad-insertion-frontend
        ports:
        - containerPort: 8080
        resources: {}
        volumeMounts:
        - name: ad-dash
          readOnly: false
          mountPath: /var/www/adinsert/dash
        - name: ad-hls
          readOnly: false
          mountPath: /var/www/adinsert/hls
      restartPolicy: Always
      volumes:
      - name: ad-dash
        hostPath:
          path: /home/vcse/ADI/fork/Ad-Insertion-Sample/volume/ad/dash
      - name: ad-hls
        hostPath:
          path: /home/vcse/ADI/fork/Ad-Insertion-Sample/volume/ad/hls
status: {}
