apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    image-pull-policy: IfNotPresent
    service.type: NodePort
  creationTimestamp: null
  labels:
    io.kompose.service: analytic-db
  name: analytic-db
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: analytic-db
    spec:
      containers:
      - image: ssai_analytic_db:latest
        imagePullPolicy: IfNotPresent
        name: analytic-db
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
