apiVersion: v1
kind: Service
metadata:
  annotations:
    image-pull-policy: IfNotPresent
    service.type: NodePort
  creationTimestamp: null
  labels:
    io.kompose.service: cdn
  name: cdn
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
    nodePort: 30443
  selector:
    io.kompose.service: cdn
  type: NodePort
status:
  loadBalancer: {}
