apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    image-pull-policy: IfNotPresent
    service.type: NodePort
  creationTimestamp:
  labels:
    io.kompose.service: cdn
  name: cdn
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp:
      labels:
        io.kompose.service: cdn
    spec:
      containers:
      - image: ssai_cdn_service:latest
        imagePullPolicy: IfNotPresent
        name: cdn
        ports:
        - containerPort: 8080
        resources: {}
        volumeMounts:
        - name: secrets
          readOnly: false
          mountPath: /var/run/secrets
      restartPolicy: Always
      volumes:
      - name: secrets
        secret:
          secretName: ssl-key-secret
status: {}
