apiVersion: v1
kind: Service
metadata:
  annotations:
    image-pull-policy: IfNotPresent
    service.type: NodePort
  creationTimestamp: null
  labels:
    io.kompose.service: content-provider-transcode
  name: content-provider-transcode
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    io.kompose.service: content-provider-transcode
  type: NodePort
status:
  loadBalancer: {}
