apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    image-pull-policy: IfNotPresent
    service.type: NodePort
  creationTimestamp:
  labels:
    io.kompose.service: content-provider
  name: content-provider
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp:
      labels:
        io.kompose.service: content-provider
    spec:
      containers:
      - image: ssai_content_provider_frontend:latest
        imagePullPolicy: IfNotPresent
        name: content-provider
        ports:
        - containerPort: 8080
        resources: {}
        volumeMounts:
        - name: html-volume
          readOnly: false
          mountPath: /var/www/html
        - name: video-archive
          readOnly: false
          mountPath: /var/www/archive
        - name: video-dash
          readOnly: false
          mountPath: /var/www/dash
        - name: video-hls
          readOnly: false
          mountPath: /var/www/hls
      restartPolicy: Always
      volumes:
      - name: html-volume
        hostPath:
          path: /home/vcse/ADI/fork/Ad-Insertion-Sample/volume/html
      - name: video-archive
        hostPath:
          path: /home/vcse/ADI/fork/Ad-Insertion-Sample/volume/video/archive
      - name: video-dash
        hostPath:
          path: /home/vcse/ADI/fork/Ad-Insertion-Sample/volume/video/dash
      - name: video-hls
        hostPath:
          path: /home/vcse/ADI/fork/Ad-Insertion-Sample/volume/video/hls
status: {}
