apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    service.type: NodePort
  creationTimestamp: null
  labels:
    io.kompose.service: database
  name: database
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: database
    spec:
      containers:
      - env:
        - name: ES_JAVA_OPTS
          value: -Xms1024m -Xmx1024m
        - name: discovery.type
          value: single-node
        image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.6.0
        name: database
        ports:
        - containerPort: 9200
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
