apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    service.type: NodePort
  creationTimestamp: null
  labels:
    io.kompose.service: kafka-init
  name: kafka-init
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: kafka-init
    spec:
      containers:
      - args:
        - bash
        - -c
        - cub kafka-ready -b kafka-service:9092 1 20 && kafka-topics --create --topic
          content_provider_sched --partitions 16 --replication-factor 1 --if-not-exists
          --zookeeper zookeeper:2181 && kafka-topics --create --topic seg_analytics_sched
          --partitions 16 --replication-factor 1 --if-not-exists --zookeeper zookeeper:2181
          && kafka-topics --create --topic seg_analytics_data --partitions 16 --replication-factor
          1 --if-not-exists --zookeeper zookeeper:2181 && kafka-topics --create --topic
          ad_transcode_sched --partitions 16 --replication-factor 1 --if-not-exists
          --zookeeper zookeeper:2181 && kafka-topics --create --topic workloads --partitions
          16 --replication-factor 1 --if-not-exists --zookeeper zookeeper:2181 &&
          kafka-topics --create --topic adstats --partitions 16 --replication-factor
          1 --if-not-exists --zookeeper zookeeper:2181 && sleep infinity
        image: confluentinc/cp-kafka:latest
        name: kafka-init
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
