apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    service.type: NodePort
  creationTimestamp: null
  labels:
    io.kompose.service: kafka-service
  name: kafka-service
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: kafka-service
    spec:
      containers:
      - env:
        - name: CONFLUENT_SUPPORT_METRICS_ENABLE
          value: "0"
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: kafka-service
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://kafka-service:9092,PLAINTEXT_HOST://localhost:29092
        - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
          value: "true"
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_DEFAULT_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_HEAP_OPTS
          value: -Xmx1024m -Xms1024m
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: PLAINTEXT
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
        - name: KAFKA_LOG4J_LOGGERS
          value: kafka=ERROR,kafka.controller=ERROR,state.change.logger=ERROR,org.apache.kafka=ERROR
        - name: KAFKA_LOG4J_ROOT_LOGLEVEL
          value: ERROR
        - name: KAFKA_LOG_RETENTION_HOURS
          value: "8"
        - name: KAFKA_NUM_PARTITIONS
          value: "16"
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zookeeper:2181
        image: confluentinc/cp-kafka:latest
        name: kafka-service
        ports:
        - containerPort: 9092
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
