apiVersion: v1
kind: Service
metadata:
  annotations:
    service.type: NodePort
  creationTimestamp: null
  labels:
    io.kompose.service: kafka-service
  name: kafka-service
spec:
  ports:
  - name: "9092"
    port: 9092
    targetPort: 9092
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    io.kompose.service: kafka-service
  type: NodePort
status:
  loadBalancer: {}
