apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    image-pull-policy: IfNotPresent
    service.type: NodePort
  creationTimestamp: null
  labels:
    io.kompose.service: video-analytic-gstreamer
  name: video-analytic-gstreamer
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: video-analytic-gstreamer
    spec:
      containers:
      - image: video_analytics_service_gstreamer:latest
        imagePullPolicy: IfNotPresent
        name: video-analytic-gstreamer
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
