apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    service.type: NodePort
  creationTimestamp: null
  labels:
    io.kompose.service: zookeeper
  name: zookeeper
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: zookeeper
    spec:
      containers:
      - env:
        - name: ZOOKEEPER_CLIENT_PORT
          value: "2181"
        - name: ZOOKEEPER_HEAP_OPTS
          value: -Xmx2048m -Xms2048m
        - name: ZOOKEEPER_LOG4J_LOGGERS
          value: zookeepr=ERROR
        - name: ZOOKEEPER_LOG4J_ROOT_LOGLEVEL
          value: ERROR
        - name: ZOOKEEPER_MAX_CLIENT_CNXNS
          value: "20000"
        - name: ZOOKEEPER_SERVER_ID
          value: "1"
        - name: ZOOKEEPER_TICK_TIME
          value: "2000"
        image: confluentinc/cp-zookeeper:latest
        name: zookeeper
        ports:
        - containerPort: 2181
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
