apiVersion: v1
kind: Service
metadata:
  annotations:
    service.type: NodePort
  creationTimestamp: null
  labels:
    io.kompose.service: zookeeper
  name: zookeeper
spec:
  ports:
  - name: "2181"
    port: 2181
    targetPort: 2181
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    io.kompose.service: zookeeper
  type: NodePort
status:
  loadBalancer: {}
