
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ad-archive
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: ad-archive
  resources:
    requests:
      storage: {{ .Values.pvc.ad.archive }}

