
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: video-cache
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: video-cache
  resources:
    requests:
      storage: {{ .Values.pvc.video.cache }}
